name: Install

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

runs:
  using: "composite"
steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Cache Yarn dependencies
    uses: actions/cache@v3
    with:
      path: ~/.yarn/cache
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
        ${{ runner.os }}-yarn-

  - name: Set up Node.js and Yarn
    uses: actions/setup-node@v3
    with:
      node-version: ${{ inputs.node-version }}
      cache: "yarn"

  - name: Install dependencies with Yarn
    run: yarn install
